{{- if .Values.metricsPort }}
{{- if .Values.monitoring.podMonitoring.enabled }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "agentmesh-node.fullname" . }}
  labels:
    {{- include "agentmesh-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agentmesh-node.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.interval }}
{{- end }}
{{- if .Values.monitoring.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "agentmesh-node.fullname" . }}
  labels:
    {{- include "agentmesh-node.labels" . | nindent 4 }}
    {{- with .Values.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "agentmesh-node.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.interval }}
{{- end }}
{{- end }}
