# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Native SDK for joining an Agent Mesh from inside a Python process."""

from .auth import (
    AUTH_PROTOCOL,
    GOAWAY_MAX_RETRY_AFTER,
    GOAWAY_PROTOCOL,
    GOAWAY_STREAM_TIMEOUT,
    MAX_GOAWAY_MESSAGE_BYTES,
    MCP_PROTOCOL,
    ROUTER_SHUN_DURATION,
    AuthRejectedError,
    auth_stream_handler,
    authenticate_with_peer,
    clamp_go_away_retry_after,
    go_away_reason_name,
    go_away_stream_handler,
)
from .authorizer import BASELINE_DATALOG, AuthorizationError, AuthorizeRequest, ProviderAuthorizerOptions, authorize_caller
from .biscuit import ROLE_ROUTER, BiscuitVerificationError, VerifiedBiscuit, attenuate_biscuit, require_role, seal_biscuit, verify_peer_biscuit
from .challenges import (
    egress_challenge,
    enroll_challenge,
    enroll_status_challenge,
    nodes_catalog_challenge,
    policies_challenge,
    refresh_challenge,
    register_challenge,
    revocations_challenge,
)
from .controlplane import (
    ROLE_NODE,
    ControlPlaneClient,
    ControlPlaneError,
    Enrollment,
    EnrollmentRejectedError,
    InsecureControlPlaneURLError,
    KeysNotTrustedError,
    RefreshResult,
    validate_control_plane_url,
    verify_keys_response,
)
from .credential import MeshCredential, decode_auth_response, encode_auth_frame
from .discovery import DHT_PROTOCOL, DiscoveredProvider, find_providers, parse_service_target, service_key
from .httpx_transport import MESH_PATH_PREFIX, MeshTransport, split_mesh_url
from .identity import Identity, canonical_peer_id, libp2p_public_key, peer_id_from_public_key, verify_ed25519
from .libp2p_http import (
    AGENT_CARD_PATH,
    DEFAULT_A2A_NAME,
    HTTP_PROTOCOL,
    A2AEndpoint,
    HTTPHandler,
    HTTPRequest,
    HTTPResponse,
    ProviderOptions,
    StreamedResponse,
    http_ingress_handler,
    http_request_over_stream,
    mesh_http_target,
    mesh_url,
    open_http_request,
    rewrite_agent_card,
)
from .mcp_client import LabelsNotSatisfiedError, ToolCallResult, ToolInfo, open_mcp_session, require_egress_labels, require_labels
from .mesh import AgentMesh, ControlPlaneSync, CredentialRetiredError, JwtSource
from .relay import dial_through_relay, reserve_relay
from .session import (
    DEFAULT_ROUTERS,
    ROUTER_REDIAL_BACKOFFS,
    AdmittedRouter,
    MeshSession,
    Peer,
    RouterCandidate,
    candidates_from_router_infos,
    select_routers,
)
from .sync import GOSSIP_EVENTS_TOPIC, BanSet, verify_mesh_event
from .tar import (
    TaskRequestContext,
    decode_tar_block_payload,
    effective_tar_expiration,
    encode_tar_block_fact,
    encode_tar_block_payload,
    evaluate_task_rules,
    match_http_path,
    match_service_pattern,
    match_task_rule,
    parse_tar_block_source,
    validate_http_grant_path,
    validate_service_pattern,
    validate_task_authorization_rule,
    validate_task_rule,
)

__version__ = "0.1.0"

__all__ = [
    "A2AEndpoint",
    "AGENT_CARD_PATH",
    "AUTH_PROTOCOL",
    "AdmittedRouter",
    "AgentMesh",
    "AuthRejectedError",
    "AuthorizationError",
    "AuthorizeRequest",
    "BASELINE_DATALOG",
    "BanSet",
    "BiscuitVerificationError",
    "ControlPlaneClient",
    "ControlPlaneError",
    "ControlPlaneSync",
    "CredentialRetiredError",
    "DEFAULT_A2A_NAME",
    "DEFAULT_ROUTERS",
    "DHT_PROTOCOL",
    "DiscoveredProvider",
    "Enrollment",
    "EnrollmentRejectedError",
    "GOAWAY_MAX_RETRY_AFTER",
    "GOAWAY_PROTOCOL",
    "GOAWAY_STREAM_TIMEOUT",
    "GOSSIP_EVENTS_TOPIC",
    "HTTP_PROTOCOL",
    "HTTPHandler",
    "HTTPRequest",
    "HTTPResponse",
    "Identity",
    "InsecureControlPlaneURLError",
    "JwtSource",
    "KeysNotTrustedError",
    "LabelsNotSatisfiedError",
    "MAX_GOAWAY_MESSAGE_BYTES",
    "MCP_PROTOCOL",
    "MESH_PATH_PREFIX",
    "MeshCredential",
    "MeshSession",
    "MeshTransport",
    "Peer",
    "ProviderAuthorizerOptions",
    "ProviderOptions",
    "ROLE_NODE",
    "ROLE_ROUTER",
    "ROUTER_REDIAL_BACKOFFS",
    "ROUTER_SHUN_DURATION",
    "RefreshResult",
    "RouterCandidate",
    "StreamedResponse",
    "TaskRequestContext",
    "ToolCallResult",
    "ToolInfo",
    "VerifiedBiscuit",
    "attenuate_biscuit",
    "auth_stream_handler",
    "authenticate_with_peer",
    "authorize_caller",
    "candidates_from_router_infos",
    "canonical_peer_id",
    "clamp_go_away_retry_after",
    "decode_auth_response",
    "decode_tar_block_payload",
    "dial_through_relay",
    "effective_tar_expiration",
    "egress_challenge",
    "encode_auth_frame",
    "encode_tar_block_fact",
    "encode_tar_block_payload",
    "enroll_challenge",
    "enroll_status_challenge",
    "evaluate_task_rules",
    "find_providers",
    "go_away_reason_name",
    "go_away_stream_handler",
    "http_ingress_handler",
    "http_request_over_stream",
    "libp2p_public_key",
    "match_http_path",
    "match_service_pattern",
    "match_task_rule",
    "mesh_http_target",
    "mesh_url",
    "nodes_catalog_challenge",
    "open_http_request",
    "open_mcp_session",
    "parse_service_target",
    "parse_tar_block_source",
    "peer_id_from_public_key",
    "policies_challenge",
    "refresh_challenge",
    "register_challenge",
    "require_egress_labels",
    "require_labels",
    "require_role",
    "reserve_relay",
    "revocations_challenge",
    "seal_biscuit",
    "select_routers",
    "service_key",
    "rewrite_agent_card",
    "split_mesh_url",
    "validate_control_plane_url",
    "validate_http_grant_path",
    "validate_service_pattern",
    "validate_task_authorization_rule",
    "validate_task_rule",
    "verify_ed25519",
    "verify_keys_response",
    "verify_mesh_event",
    "verify_peer_biscuit",
]

